export const db = [
  {
    name: '喝茶時會搭配什麼？', 
    engName: '', 
    img: '',
    description: '',
  },
  {
    name: '通常是在什麼時間？', 
    engName: '', 
    img: '',
    description: '',
  },
  {
    name: '茶色淺', 
    engName: 'Light', 
    img: '../../Images/Card/茶色淺.png',
    description: '茶湯顏色淺',
  },
  {
    name: '茶色深', 
    engName: 'Dark', 
    img: '../../Images/Card/茶色深.png',
    description: '茶湯顏色深',
  },
  {
    name: '口感較厚', 
    engName: 'Heavy', 
    img: '../../Images/Card/口感較厚.png',
    description: '入口後滋味明顯不單薄',
  },
  {
    name: '口感濃稠', 
    engName: 'Strong', 
    img: '../../Images/Card/口感濃稠.png',
    description: '滋味濃厚稠密',
  },
  {
    name: '收斂感', 
    engName: 'Convergent', 
    img: '../../Images/Card/收斂感.png',
    description: '舌尖先感受到微澀但很快化開',
  },
  {
    name: '無花果乾味', 
    engName: 'Dried Fig', 
    img: '../../Images/Card/無花果乾味.png',
    description: '清甜不膩',
  },
  {
    name: '熱帶水果味', 
    engName: 'Tropical Fruit', 
    img: '../../Images/Card/熱帶水果味.png',
    description: '果香濃厚，水果香氣重',
  },
  {
    name: '龍眼乾味', 
    engName: 'Dried Longan', 
    img: '../../Images/Card/龍眼乾味.png',
    description: '溫和甜蜜',
  },
  {
    name: '柑橘味', 
    engName: 'Tangerine', 
    img: '../../Images/Card/柑橘味.png',
    description: '酸甜香氣',
  },
  {
    name: '薄荷味', 
    engName: 'Mint', 
    img: '../../Images/Card/薄荷味.png',
    description: '清涼舒爽的香味',
  },
  {
    name: '肉桂味', 
    engName: 'Cinnamon', 
    img: '../../Images/Card/肉桂味.png',
    description: '肉桂辛香',
  },
  {
    name: '中藥味', 
    engName: 'Chinese Medicine', 
    img: '../../Images/Card/中藥味.png',
    description: '養生沉靜的香氣',
  },
  {
    name: '果酸味', 
    engName: 'Fruit Acid', 
    img: '../../Images/Card/果酸味.png',
    description: '微酸回甘的滋味',
  },
  {
    name: '草麥味',
    engName: 'Wheat',
    img: '../../Images/Card/草麥味.png',
    description: '農村稻田間的稻草麥味',
  },
  {
    name: '玄米味',
    engName: 'Brown Rice',
    img: '../../Images/Card/玄米味.png',
    description: '煎茶加炒米的清香',
  },
  
  {
    name: '蔬菜香', 
    engName: 'Vegetable', 
    img: '../../Images/Card/蔬菜香.png',
    description: '鮮甜蔬菜香氣',
  },
  {
    name: '豆子香', 
    engName: 'Bean', 
    img: '../../Images/Card/豆子香.png',
    description: '自然新鮮的豆香',
  },
  {
    name: '果香', 
    engName: 'Fruit', 
    img: '../../Images/Card/果香.png',
    description: '鮮甜水果香氣',
  },
  {
    name: '焙香', 
    engName: 'Baked', 
    img: '../../Images/Card/焙香.png',
    description: '烘烤過的香氣',
  },
  {
    name: '清香', 
    engName: 'Elegant', 
    img: '../../Images/Card/清香.png',
    description: '清新舒爽的味道',
  },
  {
    name: '野薑花香', 
    engName: 'Ginger Lily', 
    img: '../../Images/Card/野薑花香.png',
    description: '宜人清新的香氣',
  },
  {
    name: '甜香', 
    engName: 'Sweet', 
    img: '../../Images/Card/甜香.png',
    description: '香甜而不膩',
  },
  {
    name: '蜜香', 
    engName: 'Honey', 
    img: '../../Images/Card/蜜香.png',
    description: '水果散發的濃稠香氣',
  },
  {
    name: '濃郁果香', 
    engName: 'Strong Fruit', 
    img: '../../Images/Card/濃郁果香.png',
    description: '水果散發的濃稠香氣',
  },
  {
    name: '淡雅花香', 
    engName: 'Elegant Floral', 
    img: '../../Images/Card/淡雅花香.png',
    description: '新鮮優雅的花香',
  },
  {
    name: '茉莉花香',
    engName: 'Jasmine',
    img: '../../Images/Card/茉莉花香.png',
    description: '清新素雅的花香',
  },
  {
    name: '奶香',
    engName: 'Milk',
    img: '../../Images/Card/奶香.png',
    description: '似混合牛奶的乳香',
  },
  {
    name: '花香',
    engName: 'Floral',
    img: '../../Images/Card/花香.png',
    description: '花園裡的芳香',
  },
  {
    name: '青香',
    engName: 'Grass',
    img: '../../Images/Card/青香.png',
    description: '除草會散發的青草味',
  },
]