export const db = [
  {
    name: '喝茶時，會搭配什麼？', 
    engName: '', 
    img: '',
    description: '',
  },
  {
    name: '通常是在什麼時間？', 
    engName: '', 
    img: '',
    description: '',
  },
  {
    name: '蔬菜香', 
    engName: 'Vegetable', 
    img: '../../Images/Card/蔬菜香.png',
    description: '',
  },
  {
    name: '豆子', 
    engName: 'Bean', 
    img: '../../Images/Card/豆子.png',
    description: '',
  },
  {
    name: '茶色淺', 
    engName: 'Light', 
    img: '../../Images/Card/茶色淺.png',
    description: '',
  },
  {
    name: '茶色深', 
    engName: 'Dark', 
    img: '../../Images/Card/茶色深.png',
    description: '',
  },
  {
    name: '焙香', 
    engName: 'Baked', 
    img: '../../Images/Card/焙香.png',
    description: '',
  },
  {
    name: '清香', 
    engName: 'Elegant', 
    img: '../../Images/Card/清香.png',
    description: '',
  },
  {
    name: '龍眼乾', 
    engName: 'Dried Longan', 
    img: '../../Images/Card/龍眼乾.png',
    description: '',
  },
  {
    name: '無花果乾', 
    engName: 'Dried Fig', 
    img: '../../Images/Card/無花果乾.png',
    description: '',
  },
  {
    name: '熱帶果香', 
    engName: 'Tropical Fruit', 
    img: '../../Images/Card/熱帶果香.png',
    description: '',
  },
  {
    name: '果香', 
    engName: 'Fruit', 
    img: '../../Images/Card/果香.png',
    description: '',
  },
  {
    name: '口感較厚', 
    engName: 'Heavy', 
    img: '../../Images/Card/口感較厚.png',
    description: '',
  },
  {
    name: '野薑花', 
    engName: 'Ginger Lily', 
    img: '../../Images/Card/野薑花.png',
    description: '',
  },
  {
    name: '柑橘味', 
    engName: 'Tangerine', 
    img: '../../Images/Card/柑橘味.png',
    description: '',
  },
  {
    name: '薄荷', 
    engName: 'Mint', 
    img: '../../Images/Card/薄荷.png',
    description: '',
  },
  {
    name: '肉桂味', 
    engName: 'Cinnamon', 
    img: '../../Images/Card/肉桂味.png',
    description: '',
  },
  {
    name: '收斂感', 
    engName: 'Convergent', 
    img: '../../Images/Card/收斂感.png',
    description: '',
  },
  {
    name: '甜香', 
    engName: 'Sweet', 
    img: '../../Images/Card/甜香.png',
    description: '',
  },
  {
    name: '蜜香', 
    engName: 'Honey', 
    img: '../../Images/Card/蜜香.png',
    description: '',
  },
  {
    name: '中藥味', 
    engName: 'Chinese Medicine', 
    img: '../../Images/Card/中藥味.png',
    description: '',
  },
  {
    name: '濃郁果香', 
    engName: 'Strong Fruit', 
    img: '../../Images/Card/濃郁果香.png',
    description: '',
  },
  {
    name: '果酸', 
    engName: 'Fruit Acid', 
    img: '../../Images/Card/果酸.png',
    description: '',
  },
  {
    name: '口感濃稠', 
    engName: 'Strong', 
    img: '../../Images/Card/口感濃稠.png',
    description: '',
  },
  {
    name: '淡雅花香', 
    engName: 'Elegant Floral', 
    img: '../../Images/Card/淡雅花香.png',
    description: '',
  },
  {
    name: '草麥味',
    engName: 'Wheat',
    img: '../../Images/Card/草麥味.png',
    description: '',
  },
  {
    name: '玄米',
    engName: 'Brown Rice',
    img: '../../Images/Card/玄米.png',
    description: '',
  },
  {
    name: '茉莉花',
    engName: 'Jasmine',
    img: '../../Images/Card/茉莉花.png',
    description: '',
  },
  {
    name: '奶香',
    engName: 'Milk',
    img: '../../Images/Card/奶香.png',
    description: '',
  },
  {
    name: '花香',
    engName: 'Floral',
    img: '../../Images/Card/花香.png',
    description: '',
  },
  {
    name: '青香',
    engName: 'Grass',
    img: '../../Images/Card/青香.png',
    description: '',
  },
]